[package]
name = "asahi_internal"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Internal core crate for Asahi framework"

[dependencies]
thiserror = { workspace = true }
sqlx = "0.8.5"
serde_json = { workspace = true }

[features]
default = []
config = []
