name: Publish

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run'
        required: false
        default: false
        type: boolean

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

jobs:
  publish:
    name: Publish crates
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: ${{ runner.os }}-cache-v2
          cache-on-failure: 'true'
          cache-all-crates: 'true'

      - name: Log into registry
        run: cargo login $CARGO_REGISTRY_TOKEN

      - name: Publish internal first
        run: |
          if [ "${{ github.event.inputs.dry_run }}" == "true" ]; then
            cargo publish --dry-run --package asahi_internal
          else
            cargo publish --package asahi_internal
            sleep 30
          fi

      - name: Publish remaining crates
        run: |
          for crate in $(find . -name "Cargo.toml" -path "*/*" -not -path "*/internal/*" | sort); do
            echo "Publishing $crate"
            if [ "${{ github.event.inputs.dry_run }}" == "true" ]; then
              cargo publish --dry-run --manifest-path $crate
            else
              cargo publish --manifest-path $crate
              sleep 30
            fi
          done
